name: Release new package version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          access: public
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn publish
