name: Release new package version

on:
  push:
    branches:
      - main

jobs:
  npm_package:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          scope: '@igorppbr'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Configure npm registry
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmAlwaysAuth true
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build package
        run: yarn run build
      
      - name: Publish to npm
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
